import { RuleDefinition, StandardDefinition } from '../types';

export const STANDARDS_REGISTRY: StandardDefinition[] = [
  {
    id: 'iso-8100-1-2026',
    title: 'ISO 8100-1:2026 Safety rules for the construction and installation of passenger and goods passenger lifts',
    shortTitle: 'ISO 8100-1:2026',
    family: 'ISO',
    year: '2026',
    role: 'Geometry, clearances, pit, headroom, building-related boundary conditions',
    status: 'partial',
    priority: 'foundation',
    sourcePath: '/Users/edmundofrazao/MinerU/-- 01 THE REAL ISO_8100-1_032026 --.PDF-3aba5766-aac1-439d-907c-ee303340c3af/full.md',
  },
  {
    id: 'iso-8100-2-2026',
    title: 'ISO 8100-2:2026 Design rules, calculations, verifications and tests of lift components',
    shortTitle: 'ISO 8100-2:2026',
    family: 'ISO',
    year: '2026',
    role: 'Primary calculation and verification backbone',
    status: 'implemented',
    priority: 'foundation',
    sourcePath: '/Users/edmundofrazao/MinerU/-- 02 THE REAL ISO_8100-2_032026 --.PDF-f16f9639-7f67-4bdf-834a-d71dffb94e52/full.md',
  },
  {
    id: 'en-81-21-2022',
    title: 'EN 81-21:2022 New passenger and goods passenger lifts in existing buildings',
    shortTitle: 'EN 81-21:2022',
    family: 'EN',
    year: '2022',
    role: 'Existing building and reduced-clearance mode',
    status: 'planned',
    priority: 'core',
    sourcePath: '/Users/edmundofrazao/MinerU/EN 81-21-2022.pdf-b86525bf-ae54-4506-9e2d-1d212c7dcbf7/full.md',
  },
  {
    id: 'en-81-28-2022',
    title: 'EN 81-28:2022 Remote alarm on passenger and goods passenger lifts',
    shortTitle: 'EN 81-28:2022',
    family: 'EN',
    year: '2022',
    role: 'Alarm equipment, backup power, visible and audible signaling',
    status: 'partial',
    priority: 'core',
    sourcePath: '/Users/edmundofrazao/MinerU/EN 81-28-2022.pdf-64d5db31-305d-4cce-8f24-62ded42d4a00/full.md',
  },
  {
    id: 'en-81-58-2022',
    title: 'EN 81-58:2022 Landing doors fire resistance test',
    shortTitle: 'EN 81-58:2022',
    family: 'EN',
    year: '2022',
    role: 'Fire-resistance support for landing door specification',
    status: 'planned',
    priority: 'extended',
    sourcePath: '/Users/edmundofrazao/MinerU/EN 81-58-2022.pdf-0cbea116-7588-49bb-87cc-4d81da324a35/full.md',
  },
  {
    id: 'en-81-70-2022',
    title: 'EN 81-70:2021+A1:2022 Accessibility to lifts for persons including persons with disability',
    shortTitle: 'EN 81-70:2022',
    family: 'EN',
    year: '2022',
    role: 'Accessibility, car dimensions, controls, signals, equipment in the car',
    status: 'partial',
    priority: 'core',
    sourcePath: '/Users/edmundofrazao/MinerU/EN 81-70.2021+A1-2022.pdf-0f097856-622c-43e8-9597-482b717c9aa8/full.md',
  },
  {
    id: 'en-81-71-2022',
    title: 'EN 81-71:2022 Vandal resistant lifts',
    shortTitle: 'EN 81-71:2022',
    family: 'EN',
    year: '2022',
    role: 'Vandal-resistance category and hardened configuration mode',
    status: 'planned',
    priority: 'extended',
    sourcePath: '/Users/edmundofrazao/MinerU/EN 81-71-2022.pdf-33608f0d-ed97-494f-96c8-56f0c014b2c2/full.md',
  },
  {
    id: 'en-81-77-2022',
    title: 'EN 81-77:2022 Lifts subject to seismic conditions',
    shortTitle: 'EN 81-77:2022',
    family: 'EN',
    year: '2022',
    role: 'Seismic project mode, retaining devices, guide rail proof',
    status: 'partial',
    priority: 'core',
    sourcePath: '/Users/edmundofrazao/MinerU/EN 81-77-2022.pdf-a9fa13b3-8e3e-4398-80e2-1712a7bc344c/full.md',
  },
  {
    id: 'iso-8100-33-2022',
    title: 'ISO 8100-33:2022 T-type guide rails for lift cars and counterweights',
    shortTitle: 'ISO 8100-33:2022',
    family: 'ISO',
    year: '2022',
    role: 'Guide rail profiles, tolerances, fishplates, marking and dimensional catalogue',
    status: 'partial',
    priority: 'core',
    sourcePath: '/Users/edmundofrazao/MinerU/ISO 8100-33-2022.pdf-d971c464-bd61-4170-a4f7-59db52501201/full.md',
  },
];

export const RULES_REGISTRY: RuleDefinition[] = [
  {
    id: 'iso8100-1-clearances',
    standardId: 'iso-8100-1-2026',
    clause: '5 / 7',
    title: 'Hoistway clearances, pit refuge, headroom and building boundary conditions',
    subsystem: 'Hoistway & Clearances',
    applicability: ['all projects'],
    requiredInputs: ['shaftWidth', 'shaftDepth', 'pitDepth', 'headroomHeight', 'carWidth', 'carDepth', 'carHeight'],
    moduleIds: ['clearances', 'shaft', 'global'],
    status: 'partial',
    severity: 'error',
  },
  {
    id: 'iso8100-2-door-locking',
    standardId: 'iso-8100-2-2026',
    clause: '4.2',
    title: 'Verification of landing and car door locking devices',
    subsystem: 'Door Locking',
    applicability: ['all projects'],
    requiredInputs: ['doorLockingForce', 'doorMinimumEngagement', 'doorElectricalSafetyCheck'],
    moduleIds: ['doors'],
    status: 'implemented',
    severity: 'error',
  },
  {
    id: 'iso8100-2-safety-gear',
    standardId: 'iso-8100-2-2026',
    clause: '4.3',
    title: 'Verification of safety gear',
    subsystem: 'Safety Components',
    applicability: ['all projects'],
    requiredInputs: ['safetyGearMaxMass', 'safetyGearBrakingForce', 'safetyGearCertifiedSpeed'],
    moduleIds: ['safety'],
    status: 'implemented',
    severity: 'error',
  },
  {
    id: 'iso8100-2-buffers',
    standardId: 'iso-8100-2-2026',
    clause: '4.5',
    title: 'Buffer verification and stroke capacity',
    subsystem: 'Safety Components',
    applicability: ['all projects'],
    requiredInputs: ['bufferStroke', 'bufferType', 'bufferMaxMass', 'bufferMinMass', 'speed'],
    moduleIds: ['buffers'],
    status: 'implemented',
    severity: 'error',
  },
  {
    id: 'iso8100-2-acop-ucmp',
    standardId: 'iso-8100-2-2026',
    clause: '4.7 / 4.8',
    title: 'ACOP and UCMP verification',
    subsystem: 'Safety Components',
    applicability: ['electric lifts'],
    requiredInputs: ['acopType', 'acopTrippingSpeed', 'ucmpType', 'ucmpDetectionDist'],
    moduleIds: ['acop-ucmp'],
    status: 'implemented',
    severity: 'error',
  },
  {
    id: 'iso8100-2-guide-rails',
    standardId: 'iso-8100-2-2026',
    clause: '4.10',
    title: 'Guide rail design, force, displacement and verification',
    subsystem: 'Guide Rails',
    applicability: ['all projects'],
    requiredInputs: ['railArea', 'railIy', 'railIx', 'railWy', 'railWx', 'bracketDist'],
    moduleIds: ['rails-params', 'rails-forces', 'rails-verify'],
    status: 'implemented',
    severity: 'error',
  },
  {
    id: 'iso8100-2-traction',
    standardId: 'iso-8100-2-2026',
    clause: '4.11',
    title: 'Traction verification and groove pressure logic',
    subsystem: 'Traction System',
    applicability: ['electric lifts'],
    requiredInputs: ['sheaveDiameter', 'wrapAngle', 'frictionCoeff', 'sheaveHardness', 'sheaveAllowableStress'],
    moduleIds: ['traction-params', 'sheaves', 'traction-verify'],
    status: 'implemented',
    severity: 'error',
  },
  {
    id: 'iso8100-2-suspension',
    standardId: 'iso-8100-2-2026',
    clause: '4.12',
    title: 'Suspension and compensation means verification',
    subsystem: 'Suspension & Compensation Means',
    applicability: ['all projects'],
    requiredInputs: ['numRopes', 'ropeDiameter', 'ropeBreakingLoad', 'numSimpleBends', 'numReverseBends'],
    moduleIds: ['suspension-params', 'suspension-verify', 'compensation'],
    status: 'partial',
    severity: 'error',
  },
  {
    id: 'iso8100-2-hydraulic',
    standardId: 'iso-8100-2-2026',
    clause: '4.15',
    title: 'Hydraulic calculation and pressure checks',
    subsystem: 'Hydraulic Systems',
    applicability: ['hydraulic lifts'],
    requiredInputs: ['ramDiameter', 'cylinderWallThickness', 'ramLength', 'maxPressure'],
    moduleIds: ['hydraulic'],
    status: 'implemented',
    severity: 'error',
  },
  {
    id: 'iso8100-2-pessral',
    standardId: 'iso-8100-2-2026',
    clause: '4.18',
    title: 'SIL / PESSRAL logic and diagnostic coverage',
    subsystem: 'Electronics & Safety',
    applicability: ['all projects'],
    requiredInputs: ['silLevel', 'failureRate', 'diagnosticCoverage', 'dangerousFraction'],
    moduleIds: ['sil'],
    status: 'implemented',
    severity: 'warning',
  },
  {
    id: 'en8121-existing-buildings',
    standardId: 'en-81-21-2022',
    clause: '5.4 / 5.5',
    title: 'Reduced clearances and protection measures in existing buildings',
    subsystem: 'Existing Building Mode',
    applicability: ['existing buildings'],
    requiredInputs: ['pitDepth', 'headroomHeight', 'carToCounterweightClearance'],
    moduleIds: [],
    status: 'planned',
    severity: 'error',
  },
  {
    id: 'en8128-remote-alarm',
    standardId: 'en-81-28-2022',
    clause: '4.1',
    title: 'Remote alarm information, backup power and filtering',
    subsystem: 'Remote Alarms',
    applicability: ['all passenger lifts'],
    requiredInputs: ['alarmButtonType', 'alarmBackupBatteryTime', 'alarmCommunicationType', 'alarmFilteringImplemented'],
    moduleIds: ['alarms'],
    status: 'partial',
    severity: 'warning',
  },
  {
    id: 'en8158-fire-resistance',
    standardId: 'en-81-58-2022',
    clause: '4 / 5 / 6',
    title: 'Landing door fire-resistance classification and test references',
    subsystem: 'Door Fire Resistance',
    applicability: ['projects with fire-rated landing doors'],
    requiredInputs: [],
    moduleIds: [],
    status: 'planned',
    severity: 'warning',
  },
  {
    id: 'en8170-accessibility',
    standardId: 'en-81-70-2022',
    clause: '5.3 / 5.4',
    title: 'Accessibility in car dimensions, controls and signals',
    subsystem: 'Accessibility',
    applicability: ['accessible projects'],
    requiredInputs: ['carWidth', 'carDepth', 'carHeight'],
    moduleIds: ['cabin'],
    status: 'partial',
    severity: 'warning',
  },
  {
    id: 'en8171-vandal-resistant',
    standardId: 'en-81-71-2022',
    clause: '5.4 / 5.5 / 5.6',
    title: 'Vandal-resistant category, controls, doors and finishes',
    subsystem: 'Vandal Resistant Mode',
    applicability: ['vandal-resistant projects'],
    requiredInputs: [],
    moduleIds: [],
    status: 'planned',
    severity: 'warning',
  },
  {
    id: 'en8177-seismic',
    standardId: 'en-81-77-2022',
    clause: '5',
    title: 'Seismic category, retaining devices and guide rail proof',
    subsystem: 'Seismic',
    applicability: ['projects in seismic conditions'],
    requiredInputs: ['seismicCategory', 'designAcceleration', 'primaryWaveDetection'],
    moduleIds: ['seismic', 'shaft', 'rails-verify'],
    status: 'partial',
    severity: 'error',
  },
  {
    id: 'iso8100-33-guide-rail-catalogue',
    standardId: 'iso-8100-33-2022',
    clause: '6 / 7',
    title: 'Guide rail profile, tolerances, marking and fishplates',
    subsystem: 'Guide Rails',
    applicability: ['all projects'],
    requiredInputs: ['railProfile', 'railBoltDiameter', 'railNumBoltsPerJoint'],
    moduleIds: ['rails-params', 'library'],
    status: 'partial',
    severity: 'warning',
  },
];
